build: false

environment:
  matrix:
    - PHP_VERSION: 5.6
      VC_VERSION: 11
      BUILD_TYPE: nts-Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PHP_VERSION: 7.2
      VC_VERSION: 15
      BUILD_TYPE: nts-Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PHP_VERSION: 7.3
      VC_VERSION: 15
      BUILD_TYPE: nts-Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PHP_VERSION: 7.4
      VC_VERSION: 15
      BUILD_TYPE: nts-Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

  PHP_AVM: https://raw.githubusercontent.com/sergeyklay/php-appveyor/master/php-appveyor.psm1

cache:
  - 'C:\Downloads -> .appveyor.yml'

platform:
  - x64

install:
  # Download php-appveyor.psm1 module and invoke it to the current session
  - ps: (new-object Net.WebClient).DownloadString($Env:PHP_AVM) | iex
  - ps: InstallPhp        $Env:PHP_VERSION $Env:BUILD_TYPE $Env:VC_VERSION $Env:PLATFORM
  - ps: InstallComposer
  - ps: >-
      EnablePhpExtension `
        -Name       openssl
  - ps: >-
      EnablePhpExtension `
        -Name       mbstring
  - ps: $env:Path += ";C:\php"

before_test:
  - composer update --no-progress --profile -n
  - composer show

test_script:
  - vendor/bin/phpunit test